<?php


    namespace common\models;

    /**
     * Class Collection
     * @property int id
     * @property int parent_id
     * @property string cate_name
     * @property string cate_desc
     * @package common\models
     */
    class ArticleCate extends BaseActiveRecord
    {
        public static function tableName()
        {
            return "{{%article_cate}}"; // TODO: Change the autogenerated stub
        }


        public function getChild()
        {
            return $this->hasMany(ArticleCate::class, ['parent_id' => 'id'])->select(['id', 'parent_id', 'cate_name', 'cate_desc'])->with('child');
        }


    }