<?php


    namespace common\models;

    /**
     * Class Collection
     * @property int exercise_id
     * @property int cid
     * @property int top_cid
     * @property int level
     * @property int user_id
     * @package common\models
     */
    class Collection extends BaseActiveRecord
    {
        public static function tableName()
        {
            return "{{%collection}}"; // TODO: Change the autogenerated stub
        }

        public function getExercise()
        {
            return self::hasOne(OnlineExercise::class, ['id'=>'exercise_id'])->select('id, title');
        }

    }
