<?php


    namespace common\models;

    /**
     * Class Comment
     * @property integer $id
     * @property string $parent_id
     * @property string $exercise_id
     * @property string $content
     * @property string $type
     * @property string $verification_token
     * @property string $access_token
     * @property string $access_token_expir
     * @package common\models
     */
    class Comment extends BaseActiveRecord
    {

        public static function tableName()
        {
            return '{{%comment}}'; // TODO: Change the autogenerated stub
        }

        public function getExercise()
        {
            return $this->hasOne(OnlineExercise::class, ['id'=>'to_id']);
        }

        public function getUserinfo()
        {
            return $this->hasMany(User::class, ['id'=>'user_id'])->select('id, username, nickname');
        }

    }