<?php


    namespace common\models;

    /**
     * EmailSendLog model
     *
     * @property integer $id
     * @property string $email_address
     * @property string $verification_token
     * @property string $bind_username
     * @property integer $active
     * @property integer $type
     * @property integer $created_at
     * @property integer $updated_at
     */
    class EmailSendLog extends BaseActiveRecord
    {

        public static function tableName()
        {
            return '{{%email_send_log}}'; // TODO: Change the autogenerated stub
        }

    }