<?php


    namespace common\models;


    class ExerciseAnswer extends BaseActiveRecord
    {
        public static function tableName()
        {
            return "{{%online_exercise_answer}}"; // TODO: Change the autogenerated stub
        }
    }