<?php


    namespace common\models;


    class GoodsCate extends BaseActiveRecord
    {
        public static function tableName()
        {
            return "{{%goods_cate}}"; // TODO: Change the autogenerated stub
        }

        public function getChild()
        {
            return $this->hasMany(GoodsCate::class, ['parent_id' => 'id'])->select(['id', 'parent_id', 'cate_name', 'cate_desc']);
        }
    }