<?php


    namespace common\models;


    class JijingClass extends BaseActiveRecord
    {
        public static function tableName()
        {
            return "{{%jijing_class}}"; // TODO: Change the autogenerated stub
        }

        public function attributeLabels()
        {
            return [
                'id'            => 'id',
                'cate_id'       => '分类id',
                'video_title'   => '视频标题',
                'video_content' => '视频介绍',
                'video_cover'   => '视频图像',
                'video_link'    => '视频链接',
                'status'        => '视频状态',
                'created_at'    => '创建时间',
                'updated_at'    => '更新时间',
            ]; // TODO: Change the autogenerated stub
        }
    }