<?php


    namespace common\models;


    /**
     * Class OnlineExerciseAnswer
     * @property int exercise_id;
     * @property string content;
     * @property string audio_link;
     * @property int sorts;
     * @package common\models
     */
    class OnlineExerciseAnswer extends BaseActiveRecord
    {
        public static function tableName()
        {
            return "{{%online_exercise_answer}}"; // TODO: Change the autogenerated stub
        }
    }