<?php


    namespace common\models;


    class Teacher extends BaseActiveRecord
    {
        public static function tableName()
        {
            return "{{%teacher}}"; // TODO: Change the autogenerated stub
        }

        public function attributeLabels()
        {
            return [
                'id'         => 'id',
                'name'       => '名字',
                'avatar'     => '头像',
                'content'    => '教师介绍',
                'status'     => '状态',
                'created_at' => '创建时间',
                'updated_at' => '更新时间',
            ]; // TODO: Change the autogenerated stub
        }

    }