<?php


    namespace common\models;


    class VideoClassCate extends BaseActiveRecord
    {
        public static function tableName()
        {
            return "{{%video_class_cate}}"; // TODO: Change the autogenerated stub
        }

        public function attributeLabels()
        {
            return [
                'id'         => 'id',
                'parent_id'  => '父分类id',
                'cate_cover' => '分类图像',
                'cate_name'  => '分类标题',
                'cate_desc'  => '分类介绍',
                'created_at' => '创建时间',
                'updated_at' => '更新时间',
            ]; // TODO: Change the autogenerated stub
        }
    }