<?php


    namespace api\controllers;


    use common\models\Goods;
    use common\models\GoodsCate;
    use common\models\OnlineExercise;
    use common\models\OnlineExerciseCate;
    use Yii;
    use yii\data\ActiveDataProvider;
    use yii\data\Pagination;

    class GoodsController extends BaseActiveController
    {
        public $modelClass = 'common\models\Goods';

        public function actions()
        {
            $actions = parent::actions();
            unset($actions['index']);
            return $actions;
        }

        protected function verbs()
        {
            $verbs         = parent::verbs(); // TODO: Change the autogenerated stub
            $verbs['cate'] = ['GET'];
            return $verbs;
        }


        /**
         * @desc 分类列表
         * @return ActiveDataProvider
         */
        public function actionCate()
        {
            $where = ['parent_id' => 0];
            $model = GoodsCate::find()->select(['id', 'parent_id', 'cate_name', 'cate_desc'])->where($where)->asArray()->with('child');

            return new ActiveDataProvider(['query' => $model, 'pagination' => new Pagination(['pageSize' => 20])]);
        }


        /**
         * @desc 题目列表
         * @return ActiveDataProvider|mixed
         */
        public function actionIndex()
        {
            $cid   = Yii::$app->request->get('cid');
            $where = [];
            if ($cid) {
                $where['cate_id'] = $cid;
            }

            $field          = 'id, cate_id, goods_title, goods_content, goods_cover, goods_price, goods_link, status';
            $onlineExercise = Goods::find()->select($field)->where($where);

            return new ActiveDataProvider(['query' => $onlineExercise, 'pagination' => new Pagination(['pageSize' => 20])]);
        }

    }