<?php


    namespace api\controllers;

    use common\models\JijingClass;
    use common\models\VideoClassCate;
    use Yii;
    use yii\data\ActiveDataProvider;
    use yii\data\Pagination;

    class JjClassController extends BaseActiveController
    {
        public $modelClass = 'common\models\JijingClass';


        public function behaviors()
        {
            $behaviors                              = parent::behaviors();
            $behaviors['authenticator']['optional'] = ['index'];
            return $behaviors;
        }

        protected function verbs()
        {
            $verbs          = parent::verbs(); // TODO: Change the autogenerated stub
            $verbs['index'] = ['GET'];
            return $verbs;
        }

        public function actions()
        {
            $actions = parent::actions(); // TODO: Change the autogenerated stub
            unset($actions['index']);
            unset($actions['view']);
            return $actions;
        }

        public function actionIndex()
        {
            $year = Yii::$app->request->get('year', '2019');

            if (!in_array($year, ['2010','2011','2012','2010','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022','2023','2024'])){
                Yii::$app->response->statusCode = 203;
                Yii::$app->response->statusText = '年份不正确';
                return false;
            }

            $start = strtotime("$year-01-01 00:00:00");
            $end   = strtotime("$year-12-31 23:59:59");

            $start_where = [];
            $end_where = [];
            // $start_where = ['>=', 'created_at', $start];
            // $end_where   = ['<=', 'created_at', $end];

            $model = JijingClass::find()
                                ->select(['id', 'cate_id', 'video_title', 'video_content', 'video_content', 'video_cover', 'video_link', 'status', 'created_at'])
                                ->andWhere($start_where)
                                ->andWhere($end_where);
            return new ActiveDataProvider(
                [
                    'query'      => $model,
                    'pagination' => new Pagination(['pageSize' => 20])
                ]
            );
        }
    }