<?php


    namespace api\controllers;


    use common\models\OnlineExercise;
    use common\models\OnlineExerciseCate;
    use Yii;
    use yii\data\ActiveDataProvider;
    use yii\data\Pagination;
    use yii\db\Query;

    class PteOnlineExerciseController extends BaseActiveController
    {

        public $modelClass = 'common\models\OnlineExercise';

        public function behaviors()
        {
            $behaviors                              = parent::behaviors();
            $behaviors['authenticator']['optional'] = ['*'];
            return $behaviors;
        }


        protected function verbs()
        {
            $verbs             = parent::verbs(); // TODO: Change the autogenerated stub
            $verbs['exercise'] = ['GET'];
            return $verbs;
        }

        public function actions()
        {
            $actions = parent::actions();
            unset($actions['index']);
            return $actions;
        }


        /**
         * @desc 分类列表
         * @return ActiveDataProvider
         */
        public function actionCate()
        {
            $where = ['parent_id' => 0];
            $model = OnlineExerciseCate::find()
                                        ->select(['id', 'parent_id', 'cate_name', 'cate_desc'])
                                        ->where($where)
                                        ->asArray()
                                        ->with('child');

            return new ActiveDataProvider(['query' => $model, 'pagination' => new Pagination(['pageSize' => 20])]);
        }


        /**
         * @desc 题目列表
         * @return ActiveDataProvider|mixed
         */
        public function actionIndex()
        {
            $cid = Yii::$app->request->get('cid');
            if (!$cid) {
                Yii::$app->response->statusCode = 203;
                Yii::$app->response->statusText = '分类id不能为空';
                return true;
            }

            $where          = ['cate_id' => $cid];
            $onlineExercise = OnlineExercise::find()
                                            ->select('id, title, cate_id, content, video_link, status')
                                            ->where($where);
            return new ActiveDataProvider(['query' => $onlineExercise, 'pagination' => new Pagination(['pageSize' => 20])]);
        }


        public function actionView()
        {

        }


        public function actionComment()
        {
            $eid = Yii::$app->request->get('eid');
            if (!$eid) {
                Yii::$app->response->statusCode = 203;
                Yii::$app->response->statusText = '请传入题目id';
                return false;
            }

            $where          = ['id' => $eid];
            $onlineExercise = OnlineExercise::find()
                                            ->select('id, title, cate_id, content, video_link, status')
                                            ->where($where)
                                            ->one();
            return $onlineExercise;
        }


    }