<?php


    namespace api\controllers;


    use common\models\Comment;
    use common\models\OnlineExercise;
    use common\models\OnlineExerciseCate;
    use Yii;
    use yii\data\ActiveDataProvider;
    use yii\data\Pagination;
    use yii\db\Query;

    class PteOnlineExerciseController extends BaseActiveController
    {

        public $modelClass = 'common\models\OnlineExercise';

        public function behaviors()
        {
            $behaviors                              = parent::behaviors();
            $behaviors['authenticator']['optional'] = ['cate'];
            return $behaviors;
        }


        protected function verbs()
        {
            $verbs            = parent::verbs(); // TODO: Change the autogenerated stub
            $verbs['cate']    = ['GET'];
            $verbs['comment'] = ['POST'];
            return $verbs;
        }

        public function actions()
        {
            $actions = parent::actions();
            unset($actions['index']);
            unset($actions['view']);
            return $actions;
        }


        /**
         * @desc 分类列表
         * @return ActiveDataProvider
         */
        public function actionCate()
        {
            $where = ['parent_id' => 0];
            $model = OnlineExerciseCate::find()
                                       ->select(['id', 'parent_id', 'cate_name', 'cate_desc'])
                                       ->where($where)
                                       ->asArray()
                                       ->with('child');

            return new ActiveDataProvider(['query' => $model, 'pagination' => new Pagination(['pageSize' => 20])]);
        }


        /**
         * @desc 题目列表
         * @return ActiveDataProvider|mixed
         */
        public function actionIndex()
        {
            $cid     = Yii::$app->request->get('cid');
            $keyword = Yii::$app->request->get('keyword');
            if (!$cid) {
                Yii::$app->response->statusCode = 203;
                Yii::$app->response->statusText = '分类id不能为空';
                return true;
            }

            $where = ['cate_id' => $cid];

            $andWhere = ['or'];
            if ($keyword) {
                array_push($andWhere, ['like', 'title', "$keyword"]);
                array_push($andWhere, ['like', 'content', "$keyword"]);
            }

            $onlineExercise = OnlineExercise::find()
                                            ->select('id, title, cate_id, content, video_link, status, type, min_type')
                                            ->where($where)
                                            ->andWhere($andWhere);

            return new ActiveDataProvider(['query' => $onlineExercise, 'pagination' => new Pagination(['pageSize' => 20])]);
        }


        public function actionView()
        {
            $eid = Yii::$app->request->get('eid');
            if (!$eid) {
                Yii::$app->response->statusCode = 203;
                Yii::$app->response->statusText = '请传入题目id';
                return false;
            }

            $where          = ['id' => $eid];
            $onlineExercise = OnlineExercise::find()
                                            ->select('id, title, cate_id, content, video_link, status, , type, min_type')
                                            ->where($where)
                                            ->asArray()
                                            ->with('comment')
                                            ->one();
            return $onlineExercise;
        }


        public function actionComment()
        {
            $to_id   = intval(Yii::$app->request->post('to_id'));
            $type    = intval(Yii::$app->request->post('type'));
            $content = Yii::$app->request->post('content');
            if (!$to_id || !$type || !$content) {
                Yii::$app->response->statusCode = 203;
                Yii::$app->response->statusText = '参数错误';
                return false;
            }
            $isHave = OnlineExercise::findOne($to_id);
            if (!$isHave) {
                Yii::$app->response->statusCode = 203;
                Yii::$app->response->statusText = '评论对象不存在';
                return false;
            }
            $comment          = new Comment();
            $comment->to_id   = $to_id;
            $comment->type    = $type;
            $comment->content = $content;
            if (!$comment->save()) {
                $errorsValue                    = array_values($comment->getFirstErrors());
                Yii::$app->response->statusText = '发表评论失败:' . $errorsValue[0];
                return false;
            }
            return true;
        }


    }