<?php
namespace api\models;

use common\models\EmailSendLog;
use Yii;
use yii\base\Exception;
use yii\base\InvalidArgumentException;
use yii\base\Model;
use common\models\User;

/**
 * Password reset form
 */
class ResetPasswordForm extends Model
{

    public $email;
    public $password;
    public $code;

    private $_user;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['email', 'required', 'message'=>'{attribute}不能为空'],
            ['email', 'email'],

            ['password', 'required', 'message'=>'{attribute}不能为空'],
            ['password', 'string', 'min' => 6],

            ['code', 'required', 'message'=>'{attribute}不能为空'],
            ['code', 'string', 'min' => 6, 'max'=>6],
        ];
    }

    /**
     * Resets password.
     *
     * @return bool if password was reset.
     * @throws Exception
     */
    public function resetPassword()
    {
        if (!$this->validate()){
            return null;
        }

        $this->_user = User::findByEmail($this->email);
        if (!$this->_user) {
            $this->addError('code', '用户不存在');
            return false;
        }


        $transaction = Yii::$app->db->beginTransaction();

        $EmailSendLog                = EmailSendLog::findOne(['verification_token' => $this->code]);
        if (!$EmailSendLog){
            $transaction->rollBack();
            $this->addError('code', '验证码错误');
            return false;
        }

        $this->_user->setPassword($this->password);
        // $user->removePasswordResetToken();

        $EmailSendLog->active        = 2;
        $EmailSendLog->bind_username = $this->_user->username;

        if ($this->_user->save() && $EmailSendLog->save()) {
            $transaction->commit();
            return true;
        }

        $transaction->rollBack();
        return false;
    }


    public function attributeLabels()
    {
        return [
            'email'=> '邮箱',
            'password'=> '密码',
            'code'=> '验证码'
        ]; // TODO: Change the autogenerated stub
    }
}
